### ISSUE TITLE
Edit this page on GitHub

### ISSUE THREAD

**Issue by itsjuoum** [FalixNodes-Software/help-center#16]
The "Edit this page on GitHub" leads to a 404 GitHub page because, for example, it is going to `https://github.com/Falix-Software/help-center/tree/convert-to-jekyll/docs/falix/general/general.md` instead of `https://github.com/FalixNodes-Software/help-center/blob/main/docs/falix/general/general.md`

**Comment by KorbsStudio** [comment]
May be a configuration error somewhere, this will be looked into.

**Comment by KorbsStudio** [comment]
Issue found, in __config.yml__ on line 36, the branch is set to the wrong path.
Changing soon.
