### ISSUE TITLE
FalixNodes:Account-Management

### ISSUE THREAD

**Issue by LaPriseEthernet** [FalixNodes-Software/help-center#3]
I Login into falixnodes panel and its says me im not in the server. I think i was banned but  idk why i think its an error .
Pls i want help pls. My account is LaPriseEthernet#6635

**Comment by DaddyChimken** [comment]
Out of all the places you can ask for support, you choose this Github Repo??

The best place for support is our Discord server. Join with this invite link: [https://discord.gg/falixnodes](https://discord.gg/falixnodes), you can then use the `public-support` channel.

**Comment by LaPriseEthernet** [comment]
I can't accept the INVITATION!! Its the problem

**Comment by DaddyChimken** [comment]
You were banned.
Email me at `chimken@falixnodes.net` regarding this.
