### ISSUE TITLE
Inline code

### ISSUE THREAD

**Issue by Mocab** [FalixNodes-Software/help-center#46]
1- Inline code (``) does not work in tables
2- Could you add thin lines to separate rows and columns? it looks very confusing without it (refer to the screenshots attached below)
![image](https://user-images.githubusercontent.com/86360684/131435777-91c9289e-8de7-4cc0-b546-014ab261c32a.png)

**Comment by KorbsStudio** [comment]
I'll look into it later today.

**Comment by Mocab** [comment]
i have come up with a somewhat solution, only problem is i dont know scss, so i wrote the code in css
here is the code:
```
code {
    background-color:#000000 ;
    color: rgb(255, 255, 255);
    padding: 2px;
    margin: 0px;
    border: 0px;
    border-radius: 4px;
    font-size: 15px;
}
```
![image](https://user-images.githubusercontent.com/86360684/131772948-23ead146-849c-45b2-aa7d-042b2d8f3a0e.png)


We can also use other colors, i have collected some:
![image](https://user-images.githubusercontent.com/86360684/131773251-8be24329-4c40-4ccf-bf98-0d1c18d3cfb6.png)

**Comment by Mocab** [comment]
An issue that I've found is that the CSS code also affects blockquotes, we have 3 options

![image](https://user-images.githubusercontent.com/86360684/131990462-ae6a003f-0d66-4cf4-9f93-73e86311079d.png)

1- ignore it and choose a color that matches the background
2- use a class
3- use a DIV for block quotes

If we go with 1, it would look like this:
![image](https://user-images.githubusercontent.com/86360684/131991034-e66845cf-7c53-47ba-9046-9665685f4895.png)

**Comment by DaddyChimken** [comment]
Definitely not 1.
