### ISSUE TITLE
Flag:FalixNodes:Account-Management

### ISSUE THREAD

**Issue by kavin31287** [FalixNodes-Software/help-center#5]
My old accound removed after maintenance of website with 45000 mb ram 5 cpucores 63500 disk space and more. My email kav31287@gmail.com pls recover my account. My game panel password also changed .my 300 falixnodes coins gone.Also my four servers are removed Plz recover my account.pls pls. Thank You

**Comment by Ash7771430** [comment]
you just cant wait ? can you ? read announcement dude

**Comment by kavin31287** [comment]
Sorry dude I apologize .

**Comment by kavin31287** [comment]
Sry again plz send me annoucement link.
