### ISSUE TITLE
Bedrock and Java guides

### ISSUE THREAD

**Issue by Mocab** [FalixNodes-Software/help-center#51]
Bedrock guides will come to the help center soon, I was thinking of ways to sort the guides, I have come up with these permalinks:

Option 1:
/minecraft/java/general/getting-started/
/minecraft/bedrock/general/getting-started/

-----------------------------------------------------

Option 2:
/minecraft/general/java/getting-started/
/minecraft/general/bedrock/getting-started/

-----------------------------------------------------

Option 3:
Separate guides into 2 sectons, example:
### java
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor 

### bedrock
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor 

-----------------------------------------------------

If you have any suggestions, please make sure to comment them below

**Comment by itsjuoum** [comment]
I'd go for option 3

**Comment by KorbsStudio** [comment]
Option 3 is good, plus I don't want to break existing links.
Articles can be split up into two sections for bedrock and java.
I'll see what I can do later.
