### ISSUE TITLE
Search Results

### ISSUE THREAD

**Issue by Mocab** [FalixNodes-Software/help-center#56]
When you search something, The headings are connected to the paragraphs

![image](https://user-images.githubusercontent.com/86360684/132780388-b806ad70-2db5-4d10-93cf-d6f888494598.png)

When I first used the search bar, I thought that it was broken, Maybe add an alert to inform users that you have to click enter to see search results, or automatically update search results while the user is searching.

**Comment by KorbsStudio** [comment]
I'm not really sure how to fully control everything is shows in the body of the search, the help center uses Lunar Search for it's search engine. 
I will probably look into seeing what "Just the Docs" used and revamped our search engine to that again.
In the meantime, I can't really do much about Lunar Search.
