### ISSUE TITLE
Title in heading looks like an image when you haver over it

### ISSUE THREAD

**Issue by Mocab** [FalixNodes-Software/help-center#59]
### When you have over the title at the top of the screen that says "Falix Help Center" you do not see the cursor state change to the click state

What it looks like: 
![image](https://user-images.githubusercontent.com/86360684/133917497-b26f06d2-fc69-4cb0-ab05-bb41b3bbe3b2.png)

What it should look like:
![image](https://user-images.githubusercontent.com/86360684/133917521-930b8273-a986-475d-a8db-343812f888a2.png)‌
​​‌‌​‌​‌‌​​​‌‌​‌​​‌‌‌​​‌​‌‌​‌​​‌​‌​‌‌​​‌​‌​​​​​‌​​​‌‌‌​‌‌‌‌​​‌

**Comment by itsjuoum** [comment]
It's meant to be like that afaik.

**Comment by DaddyChimken** [comment]
This is due to how the text is coded. It uses an `onclick` function, so the browser does not know its an actual link.
