### ISSUE TITLE
Suggestion: Add Related articles

### ISSUE THREAD

**Issue by Mocab** [FalixNodes-Software/help-center#63]
Is there a way to add something like this as the end of every guide?

![image](https://user-images.githubusercontent.com/86360684/133959076-15a6a760-a6b4-4c3b-84fe-4154aa89349a.png)
(does not need to look like this)

We could do it manually by using something like a Metadata or we could make a bot automatically generate one based on key words in the article.

**Comment by KorbsStudio** [comment]
This is now being looked into.
